name: NodeJS Helloworld App
run-name : ${{ github.workflow }}

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: Checkout Repository
        uses: actions/Checkout@v4
        
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "18.20.0"
        
      - name: Install Dependencies
        run: |
          cd nodejs/hello
          npm install
          npm install pm2 -g

      - name: Run App with pm2
        run: |
          cd nodejs/hello
          pm2 start app.js --name "hello-app"
          pm2 save

      - name: Stop App with pm2
        run: |
          pm2 list
          pm2 stop "hello-app"
          pm2 delete "hello-app"

      #- name: Keep P<2 Alive
      #  run: |
      #    pm2 list
      #    sleep infinity